CREATE TABLE P1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  NUM INTEGER NOT NULL,
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);
PARTITION TABLE P1 ON COLUMN ID;
CREATE INDEX P1_IDX_NUM_TREE ON P1 (NUM);

CREATE TABLE R1 (
  ID INTEGER DEFAULT '0' NOT NULL,
  DESC VARCHAR(300),
  NUM INTEGER NOT NULL,
  RATIO FLOAT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE R2 (
    R2_ID INTEGER DEFAULT '0' NOT NULL,
    R2_DESC VARCHAR(300),
    R2_NUM1 INTEGER NOT NULL,
    R2_NUM2 INTEGER NOT NULL,
    PRIMARY KEY (R2_ID)
);
CREATE INDEX R2_IDX_R2NUM_TREE ON R2 (R2_NUM1,R2_NUM2);

