// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtxn.proto

package org.voltdb.pmsg;

public final class DTXN {
  private DTXN() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DependencySetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .pmsg.DependencySet.DependencyGroup dependencies = 1;
    java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> 
        getDependenciesList();
    org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup getDependencies(int index);
    int getDependenciesCount();
    java.util.List<? extends org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder> 
        getDependenciesOrBuilderList();
    org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder getDependenciesOrBuilder(
        int index);
  }
  public static final class DependencySet extends
      com.google.protobuf.GeneratedMessage
      implements DependencySetOrBuilder {
    // Use DependencySet.newBuilder() to construct.
    private DependencySet(Builder builder) {
      super(builder);
    }
    private DependencySet(boolean noInit) {}
    
    private static final DependencySet defaultInstance;
    public static DependencySet getDefaultInstance() {
      return defaultInstance;
    }
    
    public DependencySet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_fieldAccessorTable;
    }
    
    public interface DependencyGroupOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional int32 dependencyId = 1;
      boolean hasDependencyId();
      int getDependencyId();
      
      // repeated bytes dependencies = 2;
      java.util.List<com.google.protobuf.ByteString> getDependenciesList();
      int getDependenciesCount();
      com.google.protobuf.ByteString getDependencies(int index);
    }
    public static final class DependencyGroup extends
        com.google.protobuf.GeneratedMessage
        implements DependencyGroupOrBuilder {
      // Use DependencyGroup.newBuilder() to construct.
      private DependencyGroup(Builder builder) {
        super(builder);
      }
      private DependencyGroup(boolean noInit) {}
      
      private static final DependencyGroup defaultInstance;
      public static DependencyGroup getDefaultInstance() {
        return defaultInstance;
      }
      
      public DependencyGroup getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_DependencyGroup_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_DependencyGroup_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional int32 dependencyId = 1;
      public static final int DEPENDENCYID_FIELD_NUMBER = 1;
      private int dependencyId_;
      public boolean hasDependencyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDependencyId() {
        return dependencyId_;
      }
      
      // repeated bytes dependencies = 2;
      public static final int DEPENDENCIES_FIELD_NUMBER = 2;
      private java.util.List<com.google.protobuf.ByteString> dependencies_;
      public java.util.List<com.google.protobuf.ByteString>
          getDependenciesList() {
        return dependencies_;
      }
      public int getDependenciesCount() {
        return dependencies_.size();
      }
      public com.google.protobuf.ByteString getDependencies(int index) {
        return dependencies_.get(index);
      }
      
      private void initFields() {
        dependencyId_ = 0;
        dependencies_ = java.util.Collections.emptyList();;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, dependencyId_);
        }
        for (int i = 0; i < dependencies_.size(); i++) {
          output.writeBytes(2, dependencies_.get(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, dependencyId_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < dependencies_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(dependencies_.get(i));
          }
          size += dataSize;
          size += 1 * getDependenciesList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_DependencyGroup_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_DependencyGroup_fieldAccessorTable;
        }
        
        // Construct using org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          dependencyId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          dependencies_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.getDescriptor();
        }
        
        public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup getDefaultInstanceForType() {
          return org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.getDefaultInstance();
        }
        
        public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup build() {
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup buildPartial() {
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup result = new org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.dependencyId_ = dependencyId_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.dependencies_ = dependencies_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup) {
            return mergeFrom((org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup other) {
          if (other == org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.getDefaultInstance()) return this;
          if (other.hasDependencyId()) {
            setDependencyId(other.getDependencyId());
          }
          if (!other.dependencies_.isEmpty()) {
            if (dependencies_.isEmpty()) {
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDependenciesIsMutable();
              dependencies_.addAll(other.dependencies_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                dependencyId_ = input.readInt32();
                break;
              }
              case 18: {
                ensureDependenciesIsMutable();
                dependencies_.add(input.readBytes());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional int32 dependencyId = 1;
        private int dependencyId_ ;
        public boolean hasDependencyId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getDependencyId() {
          return dependencyId_;
        }
        public Builder setDependencyId(int value) {
          bitField0_ |= 0x00000001;
          dependencyId_ = value;
          onChanged();
          return this;
        }
        public Builder clearDependencyId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          dependencyId_ = 0;
          onChanged();
          return this;
        }
        
        // repeated bytes dependencies = 2;
        private java.util.List<com.google.protobuf.ByteString> dependencies_ = java.util.Collections.emptyList();;
        private void ensureDependenciesIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            dependencies_ = new java.util.ArrayList<com.google.protobuf.ByteString>(dependencies_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<com.google.protobuf.ByteString>
            getDependenciesList() {
          return java.util.Collections.unmodifiableList(dependencies_);
        }
        public int getDependenciesCount() {
          return dependencies_.size();
        }
        public com.google.protobuf.ByteString getDependencies(int index) {
          return dependencies_.get(index);
        }
        public Builder setDependencies(
            int index, com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureDependenciesIsMutable();
          dependencies_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addDependencies(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureDependenciesIsMutable();
          dependencies_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllDependencies(
            java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
          ensureDependenciesIsMutable();
          super.addAll(values, dependencies_);
          onChanged();
          return this;
        }
        public Builder clearDependencies() {
          dependencies_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:pmsg.DependencySet.DependencyGroup)
      }
      
      static {
        defaultInstance = new DependencyGroup(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:pmsg.DependencySet.DependencyGroup)
    }
    
    // repeated .pmsg.DependencySet.DependencyGroup dependencies = 1;
    public static final int DEPENDENCIES_FIELD_NUMBER = 1;
    private java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> dependencies_;
    public java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> getDependenciesList() {
      return dependencies_;
    }
    public java.util.List<? extends org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder> 
        getDependenciesOrBuilderList() {
      return dependencies_;
    }
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup getDependencies(int index) {
      return dependencies_.get(index);
    }
    public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder getDependenciesOrBuilder(
        int index) {
      return dependencies_.get(index);
    }
    
    private void initFields() {
      dependencies_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dependencies_.size(); i++) {
        output.writeMessage(1, dependencies_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < dependencies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dependencies_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.DependencySet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.voltdb.pmsg.DTXN.DependencySet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.voltdb.pmsg.DTXN.DependencySetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_DependencySet_fieldAccessorTable;
      }
      
      // Construct using org.voltdb.pmsg.DTXN.DependencySet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDependenciesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.voltdb.pmsg.DTXN.DependencySet.getDescriptor();
      }
      
      public org.voltdb.pmsg.DTXN.DependencySet getDefaultInstanceForType() {
        return org.voltdb.pmsg.DTXN.DependencySet.getDefaultInstance();
      }
      
      public org.voltdb.pmsg.DTXN.DependencySet build() {
        org.voltdb.pmsg.DTXN.DependencySet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.voltdb.pmsg.DTXN.DependencySet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.voltdb.pmsg.DTXN.DependencySet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.voltdb.pmsg.DTXN.DependencySet buildPartial() {
        org.voltdb.pmsg.DTXN.DependencySet result = new org.voltdb.pmsg.DTXN.DependencySet(this);
        int from_bitField0_ = bitField0_;
        if (dependenciesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dependencies_ = dependencies_;
        } else {
          result.dependencies_ = dependenciesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.voltdb.pmsg.DTXN.DependencySet) {
          return mergeFrom((org.voltdb.pmsg.DTXN.DependencySet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.voltdb.pmsg.DTXN.DependencySet other) {
        if (other == org.voltdb.pmsg.DTXN.DependencySet.getDefaultInstance()) return this;
        if (dependenciesBuilder_ == null) {
          if (!other.dependencies_.isEmpty()) {
            if (dependencies_.isEmpty()) {
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDependenciesIsMutable();
              dependencies_.addAll(other.dependencies_);
            }
            onChanged();
          }
        } else {
          if (!other.dependencies_.isEmpty()) {
            if (dependenciesBuilder_.isEmpty()) {
              dependenciesBuilder_.dispose();
              dependenciesBuilder_ = null;
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dependenciesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDependenciesFieldBuilder() : null;
            } else {
              dependenciesBuilder_.addAllMessages(other.dependencies_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder subBuilder = org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDependencies(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .pmsg.DependencySet.DependencyGroup dependencies = 1;
      private java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> dependencies_ =
        java.util.Collections.emptyList();
      private void ensureDependenciesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dependencies_ = new java.util.ArrayList<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup>(dependencies_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder> dependenciesBuilder_;
      
      public java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> getDependenciesList() {
        if (dependenciesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dependencies_);
        } else {
          return dependenciesBuilder_.getMessageList();
        }
      }
      public int getDependenciesCount() {
        if (dependenciesBuilder_ == null) {
          return dependencies_.size();
        } else {
          return dependenciesBuilder_.getCount();
        }
      }
      public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup getDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);
        } else {
          return dependenciesBuilder_.getMessage(index);
        }
      }
      public Builder setDependencies(
          int index, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.set(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDependencies(
          int index, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.set(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDependencies(org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDependencies(
          int index, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDependencies(
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDependencies(
          int index, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDependencies(
          java.lang.Iterable<? extends org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup> values) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          super.addAll(values, dependencies_);
          onChanged();
        } else {
          dependenciesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDependencies() {
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }
      public Builder removeDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.remove(index);
          onChanged();
        } else {
          dependenciesBuilder_.remove(index);
        }
        return this;
      }
      public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder getDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().getBuilder(index);
      }
      public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder getDependenciesOrBuilder(
          int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);  } else {
          return dependenciesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder> 
           getDependenciesOrBuilderList() {
        if (dependenciesBuilder_ != null) {
          return dependenciesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dependencies_);
        }
      }
      public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder addDependenciesBuilder() {
        return getDependenciesFieldBuilder().addBuilder(
            org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.getDefaultInstance());
      }
      public org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder addDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().addBuilder(
            index, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.getDefaultInstance());
      }
      public java.util.List<org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder> 
           getDependenciesBuilderList() {
        return getDependenciesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder> 
          getDependenciesFieldBuilder() {
        if (dependenciesBuilder_ == null) {
          dependenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder, org.voltdb.pmsg.DTXN.DependencySet.DependencyGroupOrBuilder>(
                  dependencies_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dependencies_ = null;
        }
        return dependenciesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:pmsg.DependencySet)
    }
    
    static {
      defaultInstance = new DependencySet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pmsg.DependencySet)
  }
  
  public interface ParameterSetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated bytes parameterSets = 1;
    java.util.List<com.google.protobuf.ByteString> getParameterSetsList();
    int getParameterSetsCount();
    com.google.protobuf.ByteString getParameterSets(int index);
  }
  public static final class ParameterSet extends
      com.google.protobuf.GeneratedMessage
      implements ParameterSetOrBuilder {
    // Use ParameterSet.newBuilder() to construct.
    private ParameterSet(Builder builder) {
      super(builder);
    }
    private ParameterSet(boolean noInit) {}
    
    private static final ParameterSet defaultInstance;
    public static ParameterSet getDefaultInstance() {
      return defaultInstance;
    }
    
    public ParameterSet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.voltdb.pmsg.DTXN.internal_static_pmsg_ParameterSet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.voltdb.pmsg.DTXN.internal_static_pmsg_ParameterSet_fieldAccessorTable;
    }
    
    // repeated bytes parameterSets = 1;
    public static final int PARAMETERSETS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> parameterSets_;
    public java.util.List<com.google.protobuf.ByteString>
        getParameterSetsList() {
      return parameterSets_;
    }
    public int getParameterSetsCount() {
      return parameterSets_.size();
    }
    public com.google.protobuf.ByteString getParameterSets(int index) {
      return parameterSets_.get(index);
    }
    
    private void initFields() {
      parameterSets_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < parameterSets_.size(); i++) {
        output.writeBytes(1, parameterSets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < parameterSets_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameterSets_.get(i));
        }
        size += dataSize;
        size += 1 * getParameterSetsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.voltdb.pmsg.DTXN.ParameterSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.voltdb.pmsg.DTXN.ParameterSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.voltdb.pmsg.DTXN.ParameterSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_ParameterSet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.voltdb.pmsg.DTXN.internal_static_pmsg_ParameterSet_fieldAccessorTable;
      }
      
      // Construct using org.voltdb.pmsg.DTXN.ParameterSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        parameterSets_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.voltdb.pmsg.DTXN.ParameterSet.getDescriptor();
      }
      
      public org.voltdb.pmsg.DTXN.ParameterSet getDefaultInstanceForType() {
        return org.voltdb.pmsg.DTXN.ParameterSet.getDefaultInstance();
      }
      
      public org.voltdb.pmsg.DTXN.ParameterSet build() {
        org.voltdb.pmsg.DTXN.ParameterSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.voltdb.pmsg.DTXN.ParameterSet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.voltdb.pmsg.DTXN.ParameterSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.voltdb.pmsg.DTXN.ParameterSet buildPartial() {
        org.voltdb.pmsg.DTXN.ParameterSet result = new org.voltdb.pmsg.DTXN.ParameterSet(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          parameterSets_ = java.util.Collections.unmodifiableList(parameterSets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.parameterSets_ = parameterSets_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.voltdb.pmsg.DTXN.ParameterSet) {
          return mergeFrom((org.voltdb.pmsg.DTXN.ParameterSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.voltdb.pmsg.DTXN.ParameterSet other) {
        if (other == org.voltdb.pmsg.DTXN.ParameterSet.getDefaultInstance()) return this;
        if (!other.parameterSets_.isEmpty()) {
          if (parameterSets_.isEmpty()) {
            parameterSets_ = other.parameterSets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureParameterSetsIsMutable();
            parameterSets_.addAll(other.parameterSets_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureParameterSetsIsMutable();
              parameterSets_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated bytes parameterSets = 1;
      private java.util.List<com.google.protobuf.ByteString> parameterSets_ = java.util.Collections.emptyList();;
      private void ensureParameterSetsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          parameterSets_ = new java.util.ArrayList<com.google.protobuf.ByteString>(parameterSets_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getParameterSetsList() {
        return java.util.Collections.unmodifiableList(parameterSets_);
      }
      public int getParameterSetsCount() {
        return parameterSets_.size();
      }
      public com.google.protobuf.ByteString getParameterSets(int index) {
        return parameterSets_.get(index);
      }
      public Builder setParameterSets(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterSetsIsMutable();
        parameterSets_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParameterSets(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterSetsIsMutable();
        parameterSets_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParameterSets(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParameterSetsIsMutable();
        super.addAll(values, parameterSets_);
        onChanged();
        return this;
      }
      public Builder clearParameterSets() {
        parameterSets_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pmsg.ParameterSet)
    }
    
    static {
      defaultInstance = new ParameterSet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pmsg.ParameterSet)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pmsg_DependencySet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pmsg_DependencySet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pmsg_DependencySet_DependencyGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pmsg_DependencySet_DependencyGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pmsg_ParameterSet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pmsg_ParameterSet_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndtxn.proto\022\004pmsg\"\211\001\n\rDependencySet\0229\n\014" +
      "dependencies\030\001 \003(\0132#.pmsg.DependencySet." +
      "DependencyGroup\032=\n\017DependencyGroup\022\024\n\014de" +
      "pendencyId\030\001 \001(\005\022\024\n\014dependencies\030\002 \003(\014\"%" +
      "\n\014ParameterSet\022\025\n\rparameterSets\030\001 \003(\014B\027\n" +
      "\017org.voltdb.pmsgB\004DTXN"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pmsg_DependencySet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pmsg_DependencySet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pmsg_DependencySet_descriptor,
              new java.lang.String[] { "Dependencies", },
              org.voltdb.pmsg.DTXN.DependencySet.class,
              org.voltdb.pmsg.DTXN.DependencySet.Builder.class);
          internal_static_pmsg_DependencySet_DependencyGroup_descriptor =
            internal_static_pmsg_DependencySet_descriptor.getNestedTypes().get(0);
          internal_static_pmsg_DependencySet_DependencyGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pmsg_DependencySet_DependencyGroup_descriptor,
              new java.lang.String[] { "DependencyId", "Dependencies", },
              org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.class,
              org.voltdb.pmsg.DTXN.DependencySet.DependencyGroup.Builder.class);
          internal_static_pmsg_ParameterSet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pmsg_ParameterSet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pmsg_ParameterSet_descriptor,
              new java.lang.String[] { "ParameterSets", },
              org.voltdb.pmsg.DTXN.ParameterSet.class,
              org.voltdb.pmsg.DTXN.ParameterSet.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
