package db.procedures;

import org.voltdb.SQLStmt;
import org.voltdb.VoltProcedure;
import org.voltdb.VoltTable;

public class MoveAggregatedDataToStream extends VoltProcedure {

    public final SQLStmt INSERT_SUMMARY_DATA_TO_STREAM = new SQLStmt(
        "INSERT INTO EVENTS_SUMMARY_TO_JDBC" +
            "(EVENT_INSTANCE_ID,TOATL_COUNT ,ACK_COUNT ,NACK_COUNT" +
            ",FAILED_COUNT ,DELIVERED_COUNT ,RESPONSE_COUNT" +
            ",CONVERSION_COUNT ,VALUE ,RESPONSE_COUNT_UNIQUE" +
            ",CONVERSION_COUNT_UNIQUE ,CNTL_GROUP_PART_COUNT" +
            ",CNTL_GROUP_CON_COUNT ,CNTL_GROUP_UNIQUE_CON_COUNT" +
            ",CNTL_GROUP_CON_VALUE ,RESPONSE_VALUE" +
            ",UNFORESEEN_RESPONSE_COUNT ,UNFORESEEN_CONVERSION_COUNT" +
            ",UNFORESEEN_RESPONSE_VALUE ,UNFORESEEN_CONVERSION_VALUE" +
            ",UNFORESEEN_RESP_CNT_UNIQUE ,UNFORESEEN_CONV_CNT_UNIQUE" +
            ",FULLFILLMENT_COUNT ,FULFILLMENT_FAIL_COUNT" +
            ",FULFILLMENT_FAIL_COST) " + 
         "SELECT EVENT_INSTANCE_ID,TOATL_COUNT" +
            ",ACK_COUNT ,NACK_COUNT ,FAILED_COUNT ,DELIVERED_COUNT" +
            ",RESPONSE_COUNT ,CONVERSION_COUNT ,VALUE" +
            ",RESPONSE_COUNT_UNIQUE ,CONVERSION_COUNT_UNIQUE" +
            ",CNTL_GROUP_PART_COUNT ,CNTL_GROUP_CON_COUNT" +
            ",CNTL_GROUP_UNIQUE_CON_COUNT ,CNTL_GROUP_CON_VALUE" +
            ",RESPONSE_VALUE ,UNFORESEEN_RESPONSE_COUNT" +
            ",UNFORESEEN_CONVERSION_COUNT ,UNFORESEEN_RESPONSE_VALUE" +
            ",UNFORESEEN_CONVERSION_VALUE ,UNFORESEEN_RESP_CNT_UNIQUE" +
            ",UNFORESEEN_CONV_CNT_UNIQUE ,FULLFILLMENT_COUNT" +
            ",FULFILLMENT_FAIL_COUNT ,FULFILLMENT_FAIL_COST FROM " +
            "EVENTS_SUMMARY_VW;");

    public final SQLStmt TRUNCATE_VIEW = new SQLStmt("DELETE FROM EVENTS_SUMMARY_VW;");

    public VoltTable[] run() throws VoltAbortException {
        voltQueueSQL(INSERT_SUMMARY_DATA_TO_STREAM);
        voltQueueSQL(TRUNCATE_VIEW);
        return voltExecuteSQL(true);
    }
}
